// SQL keywords organized by category

const DML_KEYWORDS = [
  'SELECT', 'FROM', 'WHERE', 'INSERT INTO', 'VALUES', 'UPDATE', 'SET',
  'DELETE FROM', 'RETURNING', 'WITH', 'RECURSIVE',
]

const JOIN_KEYWORDS = [
  'JOIN', 'LEFT JOIN', 'RIGHT JOIN', 'INNER JOIN', 'OUTER JOIN',
  'CROSS JOIN', 'FULL JOIN', 'ON', 'USING',
]

const CLAUSE_KEYWORDS = [
  'AND', 'OR', 'NOT', 'IN', 'LIKE', 'AS', 'DISTINCT',
  'ORDER BY', 'GROUP BY', 'HAVING', 'LIMIT', 'OFFSET',
  'FETCH', 'FOR UPDATE',
]

const DDL_KEYWORDS = [
  'CREATE TABLE', 'ALTER TABLE', 'DROP TABLE',
  'CREATE INDEX', 'CREATE VIEW',
]

const CONSTRAINT_KEYWORDS = [
  'PRIMARY KEY', 'FOREIGN KEY', 'REFERENCES', 'UNIQUE', 'NOT NULL',
  'DEFAULT', 'AUTO_INCREMENT', 'CASCADE', 'RESTRICT', 'CHECK',
]

const OPERATOR_KEYWORDS = [
  'BETWEEN', 'IS NULL', 'IS NOT NULL', 'EXISTS',
  'CASE', 'WHEN', 'THEN', 'ELSE', 'END',
]

const SET_OPERATION_KEYWORDS = [
  'UNION', 'UNION ALL', 'INTERSECT', 'EXCEPT',
]

const FUNCTION_KEYWORDS = [
  'COALESCE', 'NULLIF', 'CAST', 'CONVERT',
]

const WINDOW_KEYWORDS = [
  'OVER', 'PARTITION BY', 'WINDOW',
]

export const SQL_KEYWORDS: string[] = [
  ...DML_KEYWORDS,
  ...JOIN_KEYWORDS,
  ...CLAUSE_KEYWORDS,
  ...DDL_KEYWORDS,
  ...CONSTRAINT_KEYWORDS,
  ...OPERATOR_KEYWORDS,
  ...SET_OPERATION_KEYWORDS,
  ...FUNCTION_KEYWORDS,
  ...WINDOW_KEYWORDS,
]
